### ISSUE TITLE
copy-digraph

### ISSUE THREAD

**Issue by RyanBeerBarron** [sjl/cl-digraph#2]
It seems there is an error with the "copy-digraph" function in directed-graph.lisp. At line 288, it should be  "(do-edges (p s digraph) (insert-edge **copy** p s))", right?
My code wasn't working I made that change, just checking if it was intended or not.

**Comment by sjl** [comment]
Fixed in https://github.com/sjl/cl-digraph/commit/f17d719e34135f2b174a8043f8e803879071d43e -- thanks.
