### ISSUE TITLE
Suggest that topological-sort signal a meaningful condition.

### ISSUE THREAD

**Issue by psilord** [sjl/cl-digraph#5]
Could you add a meaningful and real condition for when the topological-sort fails when it detects a cycle such that it tells me the cycle it found in the condition?

Currently, I have to check for the ERROR condition and that contains all kinds of other things that could have happened during execution and is much larger of a domain that just a cycle.

Thank you!

**Comment by sjl** [comment]
Done, documentation here: https://docs.stevelosh.com/cl-digraph/usage/#conditions

**Comment by psilord** [comment]
Looks great thank you!

**Comment by mfiano** [comment]
I believe the documentation might be wrong. The name of the condition is `digraph:topological-sort-cycle` not `digraph:topological-sort-cycle-error`.

**Comment by sjl** [comment]
Fixed docs example in https://github.com/sjl/cl-digraph/commit/133aae8f913b0164faadafdad0cc650701408247
