### ISSUE TITLE
Quicklisp problem running tests.

### ISSUE THREAD

**Issue by brown** [sjl/cl-digraph#7]
SBCL outputs compiler warnings for ECASE forms lacking clauses, which causes tests to fail when run for Quicklisp.  See the second entry on this page shows the issue:  http://report.quicklisp.org/2023-11-01/failure-report.html

The problem is fixed by this pull request:  https://github.com/sjl/cl-digraph/pull/6

**Comment by sjl** [comment]
Merged the PR, thanks.

**Comment by brown** [comment]
Thanks very much for reviewing and merging the pull request.
